version: "3.8"

services:
  app:
    image: cr.yandex/<registry-id>/<image-name>:<tag>
    container_name: segmentation_app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
  postgres:
    image: postgres:latest
    container_name: postgres_segmentation
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_DB: ${DB_NAME:-segmentation}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_pp
    environment:
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_USER_PASSWORD}
volumes:
  pg_data:
